# Generated by Django 2.0.5 on 2018-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='incident',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('vibr', 'Вибросито'), ('stop', 'Остановка')], max_length=250),
        ),
    ]
