# Generated by Django 2.0.5 on 2018-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180519_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
