version: '2'
services:
  api:
    build: backend/.
    entrypoint: "./entrypoint.sh"
    command: python3 backend/manage.py runserver 0.0.0.0:8000  --insecure
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"
    depends_on:
      - db
    links:
      - db
  streamer:
    build: streamer/.
    ports:
      - "5678:5678"
    environment:
      ENCODING: "utf-8"
      FILE_PATH: "/usr/src/app/data.csv"
      COLUMNS: "date,S.C.ВПУСК.ПП.ДАВЛ...214PI226AA,ЭКСТР.ДВИГ.ВЛАСТЬ...214JI200A,УРОВЕНЬ.В...V.25001A...250LI001A,ЦИЛ..3.ТЕМП.НАГР...214TI216A"
      DATASET_PATH: "data.csv"
      DATASET_ENCODING: "utf-8"
      PREDICTION_MODEL_NAME: "./Predictions"
      VERIFICATION_MODEL_NAME: "./model1"
      IMAGES_PATH: "images"
      API_URL: "http://localhost:8000/static/"
      PERIOD: 2
      SKIP_ROWS: 40000
    volumes:
      - "./images:/usr/src/app/images"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"