version: '2'
services:
  api:
    build: backend/.
    entrypoint: "./entrypoint.sh"
    command: python3 backend/manage.py runserver 0.0.0.0:8000  --insecure
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"
    depends_on:
      - db
    links:
      - db
  streamer:
    build: streamer/.
    ports:
      - "5678:5678"
    environment:
      FILE_PATH: "/usr/src/app/crash.csv"
      COLUMNS: "date,Е.21402А....ГР.ВОДА.ВЫХ...214TIC101A,ЦИЛ..9.ТЕМП.УПР...214TIC213A,УРОВЕНЬ.В...V.25001A...250LI001A,НАГНЕТАНИЕ.В.EX.21401...250PI001"
      DATASET_PATH: "crash.csv"
      DATASET_ENCODING: "cp1251"
      PREDICTION_MODEL_NAME: "./Predictions"
      VERIFICATION_MODEL_NAME: "./model1"
      IMAGES_PATH: "images"
      API_URL: "http://localhost:8000/static/"
      PERIOD: 2
      SKIP_ROWS: 1000
    volumes:
      - "./images:/usr/src/app/images"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"