version: '2'
services:
  api:
    build: backend/.
    entrypoint: "./entrypoint.sh"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - "./backend/backend:/usr/src/app"
      - "./backend/entrypoint.sh:/usr/src/app/entrypoint.sh"
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"
    depends_on:
      - db
    links:
      - db
  streamer:
    build: streamer/.
    volumes:
      - "./streamer/data.csv:/usr/src/app/data.csv"
    ports:
      - "5678:5678"
    environment:
      ENCODING: "utf-8"
      FILE_PATH: "data.csv"
      COLUMNS: "date,S.C.ВПУСК.ПП.ДАВЛ...214PI226AA,SPEED.CONTROLLER...250MSIC001.PV,ТЕМПЕРАТУРА.EX.21401...250TI004,ЦИЛ..3.ТЕМП.НАГР...214TI216A"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"