version: '2'
services:
  api:
    build: backend/.
    entrypoint: "./entrypoint.sh"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - "./backend/backend:/code"
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "postgres"